// Code generated by piper's step-generator. DO NOT EDIT.

package cmd

import "github.com/SAP/jenkins-library/pkg/config"

// GetStepMetadata return a map with all the step metadata mapped to their stepName
func GetAllStepMetadata() map[string]config.StepData {
	return map[string]config.StepData{
		"abapAddonAssemblyKitCheck":               abapAddonAssemblyKitCheckMetadata(),
		"abapAddonAssemblyKitCheckCVs":            abapAddonAssemblyKitCheckCVsMetadata(),
		"abapAddonAssemblyKitCheckPV":             abapAddonAssemblyKitCheckPVMetadata(),
		"abapAddonAssemblyKitCreateTargetVector":  abapAddonAssemblyKitCreateTargetVectorMetadata(),
		"abapAddonAssemblyKitPublishTargetVector": abapAddonAssemblyKitPublishTargetVectorMetadata(),
		"abapAddonAssemblyKitRegisterPackages":    abapAddonAssemblyKitRegisterPackagesMetadata(),
		"abapAddonAssemblyKitReleasePackages":     abapAddonAssemblyKitReleasePackagesMetadata(),
		"abapAddonAssemblyKitReserveNextPackages": abapAddonAssemblyKitReserveNextPackagesMetadata(),
		"abapEnvironmentAssembleConfirm":          abapEnvironmentAssembleConfirmMetadata(),
		"abapEnvironmentAssemblePackages":         abapEnvironmentAssemblePackagesMetadata(),
		"abapEnvironmentBuild":                    abapEnvironmentBuildMetadata(),
		"abapEnvironmentCheckoutBranch":           abapEnvironmentCheckoutBranchMetadata(),
		"abapEnvironmentCloneGitRepo":             abapEnvironmentCloneGitRepoMetadata(),
		"abapEnvironmentCreateSystem":             abapEnvironmentCreateSystemMetadata(),
		"abapEnvironmentCreateTag":                abapEnvironmentCreateTagMetadata(),
		"abapEnvironmentPullGitRepo":              abapEnvironmentPullGitRepoMetadata(),
		"abapEnvironmentPushATCSystemConfig":      abapEnvironmentPushATCSystemConfigMetadata(),
		"abapEnvironmentRunATCCheck":              abapEnvironmentRunATCCheckMetadata(),
		"abapEnvironmentRunAUnitTest":             abapEnvironmentRunAUnitTestMetadata(),
		"abapLandscapePortalUpdateAddOnProduct":   abapLandscapePortalUpdateAddOnProductMetadata(),
		"btpCreateServiceBinding":                 btpCreateServiceBindingMetadata(),
		"btpCreateServiceInstance":                btpCreateServiceInstanceMetadata(),
		"btpDeleteServiceBinding":                 btpDeleteServiceBindingMetadata(),
		"btpDeleteServiceInstance":                btpDeleteServiceInstanceMetadata(),
		"cloudFoundryCreateServiceKey":            cloudFoundryCreateServiceKeyMetadata(),
		"cloudFoundryDeleteService":               cloudFoundryDeleteServiceMetadata(),
	}
}
