site_name: 'Project "Piper": ABAP Environment Pipeline'
nav:
    - 'Home': index.md
    - 'Getting Started With Project "Piper"' : guidedtour.md
    - 'Configuration': configuration.md
    - 'Infrastructure':
        - 'Overview': infrastructure/overview.md
        - 'Custom Jenkins Setup': infrastructure/customjenkins.md
        - 'Vault for Pipeline Secrets': infrastructure/vault.md
        - 'Fixing Docker Rate Limit': infrastructure/docker-rate-limit.md
    - 'Pipelines':
        - 'ABAP Environment pipeline':
            - 'Introduction': pipelines/abapEnvironment/introduction.md
            - 'Configuration': pipelines/abapEnvironment/configuration.md
            - 'Extensibility': pipelines/abapEnvironment/extensibility.md
            - 'Stages':
              - 'Initial Checks': pipelines/abapEnvironment/stages/initialChecks.md
              - 'Prepare System': pipelines/abapEnvironment/stages/prepareSystem.md
              - 'Clone Repositories': pipelines/abapEnvironment/stages/cloneRepositories.md
              - 'Test': pipelines/abapEnvironment/stages/test.md
              - 'Build': pipelines/abapEnvironment/stages/build.md
              - 'Integration Tests': pipelines/abapEnvironment/stages/integrationTest.md
              - 'Confirm': pipelines/abapEnvironment/stages/confirm.md
              - 'Publish': pipelines/abapEnvironment/stages/publish.md
              - 'Post': pipelines/abapEnvironment/stages/post.md
            - 'GitHub Actions': pipelines/abapEnvironment/github-actions.md
    - 'Scenarios':
        - 'Build and Publish Add-on Products on SAP BTP, ABAP Environment': scenarios/abapEnvironmentAddons.md
        - 'Continuous Testing on SAP BTP, ABAP Environment': scenarios/abapEnvironmentTest.md
    - Extensibility: extensibility.md
    - 'Library steps':
        - 'abapAddonAssemblyKit':
            - Check: steps/abapAddonAssemblyKitCheck.md
            - CheckCVs: steps/abapAddonAssemblyKitCheckCVs.md
            - CheckPV: steps/abapAddonAssemblyKitCheckPV.md
            - CreateTargetVector: steps/abapAddonAssemblyKitCreateTargetVector.md
            - PublishTargetVector: steps/abapAddonAssemblyKitPublishTargetVector.md
            - RegisterPackages: steps/abapAddonAssemblyKitRegisterPackages.md
            - ReleasePackages: steps/abapAddonAssemblyKitReleasePackages.md
            - ReserveNextPackages: steps/abapAddonAssemblyKitReserveNextPackages.md
        - abapEnvironmentAssembleConfirm: steps/abapEnvironmentAssembleConfirm.md
        - abapEnvironmentAssemblePackages: steps/abapEnvironmentAssemblePackages.md
        - abapEnvironmentBuild: steps/abapEnvironmentBuild.md
        - abapEnvironmentCheckoutBranch: steps/abapEnvironmentCheckoutBranch.md
        - abapEnvironmentCloneGitRepo: steps/abapEnvironmentCloneGitRepo.md
        - abapEnvironmentCreateSystem: steps/abapEnvironmentCreateSystem.md
        - abapEnvironmentCreateTag: steps/abapEnvironmentCreateTag.md
        - abapEnvironmentPullGitRepo: steps/abapEnvironmentPullGitRepo.md
        - abapEnvironmentPushATCSystemConfig: steps/abapEnvironmentPushATCSystemConfig.md
        - abapEnvironmentRunATCCheck: steps/abapEnvironmentRunATCCheck.md
        - abapEnvironmentRunAUnitTest: steps/abapEnvironmentRunAUnitTest.md
        - abapLandscapePortalUpdateAddOnProduct: steps/abapLandscapePortalUpdateAddOnProduct.md
        - btpCreateServiceBinding: steps/btpCreateServiceBinding.md
        - btpCreateServiceInstance: steps/btpCreateServiceInstance.md
        - btpDeleteServiceBinding: steps/btpDeleteServiceBinding.md
        - btpDeleteServiceInstance: steps/btpDeleteServiceInstance.md
        - cloudFoundryCreateServiceKey: steps/cloudFoundryCreateServiceKey.md
        - cloudFoundryDeleteService: steps/cloudFoundryDeleteService.md
    - 'Command line tool': cli/index.md

theme:
    name: 'material'
    palette:
      primary: 'teal'
      accent: 'purple'
    logo: 'images/piper_400_white.png'
    favicon: 'images/favicon.ico'
extra:
    font:
      text: 'Slabo 13px'
      code: 'Ubuntu Mono'
markdown_extensions:
    - admonition
    - attr_list
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - footnotes
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.details
extra_css:
    - 'css/extra.css'
edit_uri: edit/master/documentation/docs
site_dir: docs-gen
repo_url: https://github.com/SAP/jenkins-library
